common_params:
  learning_rate:
    type: float
    min: 1.0e-4
    max: 1.0e-2
    log: true
  weight_decay:
    type: float
    min: 1.0e-6
    max: 1.0e-2
    log: true
  batch_size:
    type: categorical
    choices: [32, 64, 128, 256]
  dropout:
    type: float
    min: 0.1
    max: 0.5

model_params:
  levels:
    type: int
    min: 2
    max: 4
  kernel_size:
    type: categorical
    choices: [3, 5, 7]
  stacks:
    type: categorical
    choices: [1, 2]

# 학습 관련 설정
patience: 15
max_epochs: 50